namespace TestDome;

internal class MalwareAnalysis
{
    public static int[] Simulate(int[] entries, int s)
    {
        if (entries == null || entries.Length == 0 || s < 0)
            throw new ArgumentException();

        var loopSize = Math.Min(entries.Length, s); // Keep from out of bounds. Would you prefer a throw in that case?
        const int newValue = -1;

        for (var i = 0; i < loopSize; i++)
        {
            entries[i] = newValue;
            entries[entries.Length - 1 - i] = newValue;
        }

        return entries;
    }

    public static void Main(string[] args)
    {
        var records = new[] { 4, 1, 3, 5, 4, 7, 9 };
        var result = Simulate(records, 3);
        Console.WriteLine(string.Join(", ", result));
    }
}
